// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://deopzprargeixoecfbea.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRlb3B6cHJhcmdlaXhvZWNmYmVhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk2MzQzNjYsImV4cCI6MjA2NTIxMDM2Nn0.JHXXl_4RvR_rgr66WKayN7TK2kzAILcRqWVk1-c8MG4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);